### ISSUE TITLE
Tribin is not working properly

### ISSUE THREAD

**Issue by andieis** [yuzie007/mpltern#14]
The tribin is calculating weird things. The output of the hexbin is correct. The main errors in the tribin are the following:
- The peak should be on the right-hand side
- The tribin is calculating in the center every second triangle with only a very low value (probably 0). In the center and right of it every triangle should be filled (You can see it too if you uncomment the lines with the scatter plot, everywhere are some datas).

As it is working with the hexbin, I assume that it is an error with the tribin and not with my data.

To reproduce it, you find attached the code I'm running, as well as the data and a screenshot of my output. Thanks for any help in advance!

Kind regards,
Andreas

![grafik](https://github.com/yuzie007/mpltern/assets/28967379/86654a17-0b06-4dd0-84d4-da692f356c78)

```
import numpy as np
import matplotlib.pyplot as plt
import mpltern
import csv

with open("data.csv", "r") as file:
    csv_dict = np.array(list(csv.reader(file)))

t = csv_dict[:,0]
t = np.array([int(i) for i in t]) / 4500
l = csv_dict[:,2]
l = np.array([float(i) for i in l]) / 360
r = csv_dict[:,1]
r = np.array([float(i) for i in r]) / 70

fig = plt.figure(figsize=(10.8, 4.8))
fig.subplots_adjust(left=0.075, right=0.85, wspace=0.3)

ax = fig.add_subplot(1, 2, 1, projection="ternary")
# ax.scatter(t, l, r, color="C3", marker="x")
pc = ax.hexbin(t, l, r, gridsize=10, edgecolors="k", alpha=0.5, zorder=0.0)
ax.set_title("hexbin")
ax.taxis.set_ticks(np.array([0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]) / 4500, labels=(0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500))
ax.laxis.set_ticks(np.array([0, 45, 90, 135, 180, 225, 270, 315, 360]) / 360, labels=(0, 45, 90, 135, 180, 225, 270, 315, 360))
ax.raxis.set_ticks(np.array([0, 10, 20, 30, 40, 50, 60, 70]) / 70, labels=(0, 10, 20, 30, 40, 50, 60, 70))

cax = ax.inset_axes([1.05, 0.1, 0.05, 0.9], transform=ax.transAxes)
colorbar = fig.colorbar(pc, cax=cax)
colorbar.set_label("Count", rotation=270, va="baseline")

ax = fig.add_subplot(1, 2, 2, projection="ternary")
# ax.scatter(t, l, r, color="C3", marker="x")
pc = ax.tribin(t, l, r, gridsize=10, edgecolors="k", alpha=0.5, zorder=0.0)
ax.set_title("tribin")
ax.taxis.set_ticks(np.array([0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]) / 4500, labels=(0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500))
ax.laxis.set_ticks(np.array([0, 45, 90, 135, 180, 225, 270, 315, 360]) / 360, labels=(0, 45, 90, 135, 180, 225, 270, 315, 360))
ax.raxis.set_ticks(np.array([0, 10, 20, 30, 40, 50, 60, 70]) / 70, labels=(0, 10, 20, 30, 40, 50, 60, 70))

cax = ax.inset_axes([1.05, 0.1, 0.05, 0.9], transform=ax.transAxes)
colorbar = fig.colorbar(pc, cax=cax)
colorbar.set_label("Count", rotation=270, va="baseline")

plt.show()
```

[data.csv](https://github.com/yuzie007/mpltern/files/13606145/data.csv)

**Comment by yuzie007** [comment]
Thank you @andieis for your report.
While I also reproduced your plots, can I have one question before further survey?
In your `data.csv`, the sums of three columns are not a constant but different for rows.
To my best knowledge it is not very common for [ternary plots](https://en.wikipedia.org/wiki/Ternary_plot).
Can I ask how is your use-case of ternary plots?

**Comment by andieis** [comment]
Well, you are right - they do not sum up to a constant value for each row.

I just would like to show 4-dimensional data in a easily understandable way.

As I studied now a bit more into detail, I realized that my goal cannot be achieved using a ternary plot, as it does not sum up to a constant value.

Thanks anyways for your answer and your work!

**Comment by yuzie007** [comment]
While it was not directly your concern, with this issue, I noticed that the normalization was not properly done as expected in `hexbin` and `tribin`. In the latest version `1.0.3`, this is fixed. With this, I would like to close this issue. In case you find some issue, please feel free to re-open this issue or open a new issue. Thank you @andieis once again for your report and trying `mpltern`!
