### ISSUE TITLE
Add new publication to the 'Publications Using mpltern' list.

### ISSUE THREAD

**Issue by kaarelmand** [yuzie007/mpltern#4]
A publication that I authored recently made use of and cited the `mpltern` package. You can find it on this link:

https://www.mdpi.com/2075-163X/11/4/368/htm

The DOI link is still being registered: https://doi.org/10.3390/min11040368

**Comment by yuzie007** [comment]
Thank you so much @kaarelmand for using `mpltern`. Congratulations for your recent publication! I added the paper in the publication list https://mpltern.readthedocs.io/en/latest/publications.html.

**Comment by kaarelmand** [comment]
Thanks a lot!
